name = "MatrixBandwidth"
uuid = "075aa41b-24fd-4573-b25f-92cae432c0f8"
keywords = ["matrix bandwidth", "sparse matrices", "optimization", "scientific computing", "julia"]
license = "MIT"
authors = ["Luis M. B. Varona <lm.varona@outlook.com>"]
description = "Fast algorithms for matrix bandwidth minimization and recognition, written in Julia."
homepage = "https://luis-varona.github.io/MatrixBandwidth.jl/"
maintainers = ["Luis M. B. Varona <lm.varona@outlook.com>"]
readme = "README.md"
repository = "https://github.com/Luis-Varona/MatrixBandwidth.jl"
version = "0.2.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Combinatorics = "1.0"
DataStructures = "0.18.15 - 0.19"
HiGHS = "1.8.0"
JuMP = "1.18"
PrecompileTools = "1.2"
Random = "1.10"
julia = "1.10"
