name: Draft PDF
on:
  push:
    branches:
      - joss
    paths:
      - joss/**
      - .github/workflows/draft-pdf.yml
permissions:
  contents: write
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: joss/paper.md
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: paper
          path: joss/paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: 'joss/paper.pdf'
